[package]
name = "zex-shell"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Zex shell daemon and CLI"

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
clap = { version = "4", features = ["derive"] }
zex-core = { path = "../zex-core" }
zex-services = { path = "../zex-services" }
zex-launcher = { path = "../zex-launcher" }
flume = "0.11"
tokio.workspace = true
zbus = { version = "5.19", features = ["tokio"] }
gtk4.workspace = true
gdk-pixbuf.workspace = true
grass.workspace = true
gtk4-layer-shell.workspace = true
glib.workspace = true
relm4.workspace = true
libc.workspace = true

[[bin]]
name = "zex"
path = "src/main.rs"

[[bin]]
name = "zexctl"
path = "src/bin/zexctl.rs"
