[package]
name = "zex-shell"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Zex shell daemon and CLI"

[dependencies]
anyhow.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
clap = { version = "4", features = ["derive"] }
zex-core = { path = "../zex-core" }
zex-services = { path = "../zex-services" }
zex-launcher = { path = "../zex-launcher" }
flume = "0.11"
tokio.workspace = true
tokio-util.workspace = true
tarpc.workspace = true
zbus = { version = "5.19", features = ["tokio", "blocking"] }
rust-embed.workspace = true
chrono.workspace = true
image.workspace = true
libc.workspace = true
zeroize.workspace = true

# iced stack
iced.workspace = true
iced_exwlshell.workspace = true
iced_wgpu.workspace = true
iced_core.workspace = true
iced_widget.workspace = true
iced_graphics.workspace = true
iced_runtime.workspace = true
iced_futures.workspace = true
iced_renderer.workspace = true

[[bin]]
name = "zex-shell"
path = "src/main.rs"

[[bin]]
name = "zexctl"
path = "src/bin/zexctl.rs"