[package]
name = "zex-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Zex core"

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
dirs.workspace = true
grass.workspace = true
tokio.workspace = true
gtk4.workspace = true
